<?php

namespace App\Console\Commands;

use App\Models\Category;
use App\Models\Task;
use App\Models\TaskHistory;
use App\Models\User;
use App\Models\WeeklyRecommendation;
use App\Services\TaskService;
use Carbon\Carbon;
use Illuminate\Console\Command;
use Illuminate\Support\Facades\Http;
use Illuminate\Support\Facades\Log;

class GenerateTaskRecommendations extends Command
{
    /**
     * The name and signature of the console command.
     *
     * @var string
     */
    protected $signature = 'app:generate-task-recommendations {user_id : The ID of the user to generate recommendations for}';

    /**
     * The console command description.
     *
     * @var string
     */
    protected $description = 'Generate task recommendations for a user using Remi AI Task Suggestion Agent API';

    /**
     * Execute the console command.
     */
    public function handle(TaskService $taskService)
    {
        $userId = $this->argument('user_id');
        $user = User::find($userId);

        if (! $user) {
            $this->error("User with ID {$userId} not found.");

            return 1;
        }

        $this->info("Generating recommendations for user: {$user->name}");

        // Determine the current week's start date (Monday)
        $weekStartDate = Carbon::now()->startOfWeek()->format('Y-m-d');

        // Check if recommendations already exist for this user and week
        $existingRecommendation = WeeklyRecommendation::where('user_id', $userId)
            ->where('week_start_date', $weekStartDate)
            ->first();

        if ($existingRecommendation) {
            if (! $this->confirm('Recommendations already exist for this week. Do you want to regenerate them?')) {
                $this->info('Operation canceled.');

                return 0;
            }

            // Delete existing recommended tasks
            $existingRecommendation->recommendedTasks()->delete();
            $existingRecommendation->delete();
        }

        // Check if user has tasks
        $taskCount = Task::where('user_id', $userId)->count();

        if ($taskCount === 0) {
            $this->warn('No tasks found for this user.');

            return 0;
        }

        // Fetch tasks that are due for completion (default: 7 days)
        $this->info('Fetching tasks that are due for completion...');
        $tasks = $taskService->getTasksDueForUser($user, 7);

        if ($tasks->isEmpty()) {
            $this->info('No tasks are currently due for completion.');

            return 0;
        }

        $this->info("Found {$tasks->count()} tasks that are due for completion.");

        // Prepare data for API request
        $this->info('Preparing data for API request...');
        $apiData = $this->prepareApiData($user, $weekStartDate, $tasks);

        // Generate recommendations using Remi AI
        $this->info('Generating AI recommendations via Remi AI...');
        try {
            $response = Http::timeout(60)->post(config('remi-ai.base_url') . '/agents/task-suggestion-agent/default', $apiData);

            if (! $response->successful()) {
                $this->error('API request failed: ' . $response->status() . ' - ' . $response->body());

                return 1;
            }

            $apiResponse = $response->json();

            if (! isset($apiResponse['recommended_tasks']) || empty($apiResponse['recommended_tasks'])) {
                $this->info('No recommendations were generated by the API.');

                return 0;
            }

            // Create a new weekly recommendation
            $weeklyRecommendation = WeeklyRecommendation::create([
                'user_id' => $userId,
                'week_start_date' => $weekStartDate,
                'generated_at' => now(),
            ]);

            // Create recommended tasks from API response
            $count = 0;
            foreach ($apiResponse['recommended_tasks'] as $recommendedTask) {
                if (! isset($recommendedTask['task_id'], $recommendedTask['priority'], $recommendedTask['reason'])) {
                    $this->warn('Skipping recommendation with missing required fields: ' . json_encode($recommendedTask));

                    continue;
                }

                $weeklyRecommendation->recommendedTasks()->create([
                    'task_id' => $recommendedTask['task_id'],
                    'priority' => $recommendedTask['priority'],
                    'reason' => $recommendedTask['reason'],
                    'completed' => false,
                ]);
                $count++;
            }

            if ($count > 0) {
                $this->info("Created {$count} task recommendations for the week starting {$weekStartDate}.");
            } else {
                $this->warn('No valid recommendations were created.');
            }
        } catch (\Exception $e) {
            $this->error('Error calling Remi AI API: ' . $e->getMessage());
            Log::error('GenerateTaskRecommendations API Error', [
                'error' => $e->getMessage(),
                'user_id' => $userId,
                'week_start_date' => $weekStartDate,
            ]);

            return 1;
        }

        return 0;
    }

    /**
     * Prepare data for the API request
     */
    private function prepareApiData(User $user, string $weekStartDate, $tasks): array
    {
        // Get all categories for the user
        $categories = Category::where('user_id', $user->id)->get();

        // Get task IDs to fetch task histories
        $taskIds = $tasks->pluck('id')->toArray();

        // Get task histories for the last 6 months
        $sixMonthsAgo = Carbon::now()->subMonths(6);
        $taskHistories = TaskHistory::whereIn('task_id', $taskIds)
            ->where('completed_at', '>=', $sixMonthsAgo)
            ->orderBy('completed_at', 'desc')
            ->get();

        // Format tasks for API
        $formattedTasks = $tasks->map(function ($task) {
            return [
                'id' => $task->id,
                'user_id' => $task->user_id,
                'category_id' => $task->category_id,
                'title' => $task->title,
                'timing_description' => $task->timing_description,
                'last_completed_at' => $task->last_completed_at?->toISOString(),
                'created_at' => $task->created_at->toISOString(),
                'updated_at' => $task->updated_at->toISOString(),
            ];
        })->toArray();

        // Format categories for API
        $formattedCategories = $categories->map(function ($category) {
            return [
                'id' => $category->id,
                'user_id' => $category->user_id,
                'name' => $category->name,
                'color' => $category->color,
                'created_at' => $category->created_at->toISOString(),
                'updated_at' => $category->updated_at->toISOString(),
            ];
        })->toArray();

        // Format task histories for API
        $formattedTaskHistories = $taskHistories->map(function ($history) {
            return [
                'id' => $history->id,
                'task_id' => $history->task_id,
                'completed_at' => $history->completed_at->toISOString(),
                'notes' => $history->notes,
                'created_at' => $history->created_at->toISOString(),
                'updated_at' => $history->updated_at->toISOString(),
            ];
        })->toArray();

        return [
            'user_id' => $user->id,
            'week_start_date' => Carbon::parse($weekStartDate)->startOfWeek()->toISOString(),
            'tasks' => $formattedTasks,
            'categories' => $formattedCategories,
            'task_histories' => $formattedTaskHistories,
        ];
    }
}
